version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: OhioVoter/OhioVoter/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: OhioVoter/OhioVoter/scripts/start_server
      timeout: 300
      runas: root
   AfterInstall:
    - location: OhioVoter/OhioVoter/scripts/stop_server
      timeout: 300
      runas: root
      
   
